var TREE_ITEMS = [
['History/Geography: Railways and Social Change in France and Great Britain, 1830-1930', '2_.htm',{'tw':'basefrm'},
  ['Introduction', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Introduction.htm',{'tw':'basefrm'},
  ],
  ['Participants', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Participants.htm',{'tw':'basefrm'}],
  ['Essays for Publication', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Essays_for_Publication.htm',{'tw':'basefrm'},
    ['Railways, Uneven Development, and Globalization', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Essays_for_Publication/Railways,_Uneven_Development,_and_Globalization.htm',{'tw':'basefrm'}],
    ['National Historical Geographical Information System', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Essays_for_Publication/National_Historical_Geographical_Information_System.htm',{'tw':'basefrm'}],
    ['Teaching Environmental History with GIS', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Essays_for_Publication/Teaching_Environmental_History_with_GIS.htm',{'tw':'basefrm'}],
    ['Rail Transport, Agrarian Crisis, and the Reorganization of Agriculture', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Essays_for_Publication/Rail_Transport,_Agrarian_Crisis,_and_the_Reorganization_of_Agriculture.htm',{'tw':'basefrm'}],
    ['New Tools for Clio', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Essays_for_Publication/New_Tools_for_Clio.htm',{'tw':'basefrm'}],
  ],
  ['Maps & Graphs', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Maps___Graphs.htm',{'tw':'basefrm'},
    ['Maps', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Maps___Graphs/Maps.htm',{'tw':'basefrm'}],
    ['Graphs', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Maps___Graphs/Graphs.htm',{'tw':'basefrm'}],
  ],
  ['Railways', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways.htm',{'tw':'basefrm'},
    ['Overview', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways/Overview.htm',{'tw':'basefrm'}],
    ['England and Wales', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways/England_and_Wales.htm',{'tw':'basefrm'}],
    ['France', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways/France.htm',{'tw':'basefrm'}],
  ],
  ['Population Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change.htm',{'tw':'basefrm'},
    ['England and Wales', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change/England_and_Wales.htm',{'tw':'basefrm'},
      ['Historical GIS and Infant Mortality Decline', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change/England_and_Wales/Historical_GIS_and_Infant_Mortality_Decline.htm',{'tw':'basefrm'}],
      ['Spatial Analysis ofLlong-term Demographic Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change/England_and_Wales/Spatial_Analysis_ofLlong-term_Demographic_Change.htm',{'tw':'basefrm'}],
    ],
    ['France', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change/France.htm',{'tw':'basefrm'},
      ['Geography of Population Change in France, 1851-1931', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change/France/Geography_of_Population_Change_in_France,_1851-1931.htm',{'tw':'basefrm'}],
      ['Estimating historical population densities over time', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Population_Change/France/Estimating_historical_population_densities_over_time.htm',{'tw':'basefrm'}],
    ],
  ],
  ['Uneven Development', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Uneven_Development.htm',{'tw':'basefrm'},
    ['Spatial Political Economy', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Uneven_Development/Spatial_Political_Economy.htm',{'tw':'basefrm'}],
  ],
  ['Railways and Population Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Population_Change.htm',{'tw':'basefrm'},
    ['Demographic Change and Railway Expansion:', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Population_Change/Demographic_Change_and_Railway_Expansion_.htm',{'tw':'basefrm'}],
    ['Population change and transport in Wales', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Population_Change/Population_change_and_transport_in_Wales.htm',{'tw':'basefrm'}],
    ['Population change and transport in rural England & Wales,1825-1911', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Population_Change/Population_change_and_transport_in_rural_England___Wales,1825-1911.htm',{'tw':'basefrm'}],
  ],
  ['Railways and Agrarian Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Agrarian_Change.htm',{'tw':'basefrm'},
    ['England and Wales', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Agrarian_Change/England_and_Wales.htm',{'tw':'basefrm'}],
    ['France', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Agrarian_Change/France.htm',{'tw':'basefrm'}],
    ['Producing Space and Making Place', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Railways_and_Agrarian_Change/Producing_Space_and_Making_Place.htm',{'tw':'basefrm'}],
  ],
  ['Scales of Analysis: From Global to Local', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Scales_of_Analysis__From_Global_to_Local.htm',{'tw':'basefrm'},
    ['Narratives of Place', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Scales_of_Analysis__From_Global_to_Local/Narratives_of_Place.htm',{'tw':'basefrm'}],
  ],
  ['Globalization and Agrarian Crisis', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Globalization_and_Agrarian_Crisis.htm',{'tw':'basefrm'},
    ['From Global to Local: Railways and Agrarian Crisis', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Globalization_and_Agrarian_Crisis/From_Global_to_Local__Railways_and_Agrarian_Crisis.htm',{'tw':'basefrm'}],
    ['Agrarian Crisis AHA paper 2007', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Globalization_and_Agrarian_Crisis/Agrarian_Crisis_AHA_paper_2007.htm',{'tw':'basefrm'}],
    ['Railways and Agrarian Crisis', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Globalization_and_Agrarian_Crisis/Railways_and_Agrarian_Crisis.htm',{'tw':'basefrm'}],
    ['Agrarian Crisis & Small Farming', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Globalization_and_Agrarian_Crisis/Agrarian_Crisis___Small_Farming.htm',{'tw':'basefrm'}],
  ],
  ['Cultural Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Cultural_Change.htm',{'tw':'basefrm'},
    ['Representations of Space and Place', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Cultural_Change/Representations_of_Space_and_Place.htm',{'tw':'basefrm'}],
    ['Discovering the Countryside', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Cultural_Change/Discovering_the_Countryside.htm',{'tw':'basefrm'}],
  ],
  ['Historical GIS', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Historical_GIS.htm',{'tw':'basefrm'},
    ['National HGIS', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Historical_GIS/National_HGIS.htm',{'tw':'basefrm'}],
    ['Teaching Environmental History with Historical GIS', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Historical_GIS/Teaching_Environmental_History_with_Historical_GIS.htm',{'tw':'basefrm'}],
  ],
  ['Student Research Projects', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects.htm',{'tw':'basefrm'},
    ['Bresnick Salt Mines & Subsidence in Northwich', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Bresnick_Salt_Mines___Subsidence_in_Northwich.htm',{'tw':'basefrm'}],
    ['Fuchs Ninetheenth-Century Swansea', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Fuchs_Ninetheenth-Century_Swansea.htm',{'tw':'basefrm'}],
    ['Joyce Wolverton and Wolverhampton', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Joyce_Wolverton_and_Wolverhampton.htm',{'tw':'basefrm'}],
    ['Calament Lead Mining & Population Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Calament_Lead_Mining___Population_Change.htm',{'tw':'basefrm'}],
    ['Gottschall Railways, Tourism, and Migration', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Gottschall_Railways,_Tourism,_and_Migration.htm',{'tw':'basefrm'}],
    ['Hafernik Railway Travel and Migration', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Hafernik_Railway_Travel_and_Migration.htm',{'tw':'basefrm'}],
    ['Lindsay Agriculture in Norfolk', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Lindsay_Agriculture_in_Norfolk.htm',{'tw':'basefrm'}],
    ['Moon Change in the Lake District', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Moon_Change_in_the_Lake_District.htm',{'tw':'basefrm'}],
    ['Socinski Landscapes of Leisure', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Socinski_Landscapes_of_Leisure.htm',{'tw':'basefrm'}],
    ['Joyce Agrarian Change in Kent', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Joyce_Agrarian_Change_in_Kent.htm',{'tw':'basefrm'}],
    ['Stafford Bethal Green', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Stafford_Bethal_Green.htm',{'tw':'basefrm'}],
    ['Gottschall Economic and Ecological Transformation', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Gottschall_Economic_and_Ecological_Transformation.htm',{'tw':'basefrm'}],
    ['Parks Railways and Change in Evesham', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Parks_Railways_and_Change_in_Evesham.htm',{'tw':'basefrm'}],
    ['Gillaspie Railways, Fishing, and Population Change', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Student_Research_Projects/Gillaspie_Railways,_Fishing,_and_Population_Change.htm',{'tw':'basefrm'}],
  ],
  ['Bibliography', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Bibliography.htm',{'tw':'basefrm'}],
  ['Links', 'History_Geography__Railways_and_Social_Change_in_France_and_Great_Britain,_1830-1930/Links.htm',{'tw':'basefrm'}],
],
];
